version: "3.9"

services:
  prodigy-tone:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual tone ./datasets/tone.jsonl --label negative,neutral,positive --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.prodigy-tone.rule=Host(`fusion-tone.quesmed.com`)
        - traefik.http.routers.prodigy-tone.tls=true
        - traefik.http.routers.prodigy-tone.middlewares=https_redirect@file
        - traefik.http.services.prodigy-tone-service.loadbalancer.server.port=8080

  prodigy-emotion:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual emotion ./datasets/emotion.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.prodigy-emotion.rule=Host(`fusion-emotion.quesmed.com`)
        - traefik.http.routers.prodigy-emotion.tls=true
        - traefik.http.routers.prodigy-emotion.middlewares=https_redirect@file
        - traefik.http.services.prodigy-emotion-service.loadbalancer.server.port=8080

  prodigy-theme:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual theme ./datasets/theme.jsonl --label clinical_update,community,question,education,advocating,dissuading,other --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.prodigy-theme.rule=Host(`fusion-theme.quesmed.com`)
        - traefik.http.routers.prodigy-theme.tls=true
        - traefik.http.routers.prodigy-theme.middlewares=https_redirect@file
        - traefik.http.services.prodigy-theme-service.loadbalancer.server.port=8080
