version: "3.9"

services:
  prodigy-tone:
    image: prodigy-fusion
    container_name: prodigy-tone
    command: prodigy textcat.manual tone ./datasets/tone.jsonl --label negative,neutral,positive --exclusive
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - pg-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.quesmed-api.rule=Host(`fusion-tone.quesmed.com`)
        - traefik.http.routers.quesmed-api.tls=true
        - traefik.http.routers.quesmed-api.middlewares=https_redirect@file
        - traefik.http.services.quesmed-api-service.loadbalancer.server.port=8080

  prodigy-emotion:
    image: prodigy-fusion
    container_name: prodigy-emotion
    command: prodigy textcat.manual emotion ./datasets/emotion.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - pg-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.quesmed-api.rule=Host(`fusion-emotion.quesmed.com`)
        - traefik.http.routers.quesmed-api.tls=true
        - traefik.http.routers.quesmed-api.middlewares=https_redirect@file
        - traefik.http.services.quesmed-api-service.loadbalancer.server.port=8081

  prodigy-theme:
    image: prodigy-fusion
    container_name: prodigy-theme
    command: prodigy textcat.manual theme ./datasets/theme.jsonl --label clinical_update,community,question,education,advocating,dissuading,other --exclusive
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - pg-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.quesmed-api.rule=Host(`fusion-theme.quesmed.com`)
        - traefik.http.routers.quesmed-api.tls=true
        - traefik.http.routers.quesmed-api.middlewares=https_redirect@file
        - traefik.http.services.quesmed-api-service.loadbalancer.server.port=8082

  postgres:
    image: postgres:16-alpine
    container_name: pg-fusion
    restart: unless-stopped
    env_file: .env
    ports:
      - target: 5432
        published: 5432
    networks:
      - pg-network
    volumes:
      - pgdata16:/var/lib/postgresql/data

volumes:
  pgdata16:

networks:
  pg-network:
    driver: bridge
