version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    environment:
      WHOAMI_PORT_NUMBER: 8081
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.services.whoami-service.loadbalancer.server.port=8081

  fusion-tone:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual tone ./datasets/tone.jsonl --label negative,neutral,positive --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.fusion-tone.rule=Host(`fusion-tone.localhost`)
      - traefik.http.services.fusion-tone-service.loadbalancer.server.port=8080

  fusion-emotion:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual emotion ./datasets/emotion.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.fusion-emotion.rule=Host(`fusion-emotion.localhost`)
      - traefik.http.services.fusion-emotion-service.loadbalancer.server.port=8080

  fusion-theme:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-fusion:latest
    command: prodigy textcat.manual theme ./datasets/theme.jsonl --label clinical_update,community,question,education,advocating,dissuading,other --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.fusion-theme.rule=Host(`fusion-theme.localhost`)
      - traefik.http.services.fusion-theme-service.loadbalancer.server.port=8080
